In [2]:
from numpy  import *
b = array([1,2,3,4,5,6, 7, 8]);
b


array([1, 2, 3, 4, 5, 6, 7, 8])

## Reshape an array

In [3]:
c=b.reshape(2,4);
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Operations between arrays

Operations between two arrays are performed in an element-wise manner, which means $A_{ij}=B_{ij} op C_{ij}$. This is different from the actual definitions of operations between matrixes. This kind of operations include +,-,*,/.

In [4]:
d=array([7,8,9,10,11,12,13,14]).reshape(2,4)
d+c

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [5]:
d-c

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

## Built in operations of an array

Array has built in operations to calculate values related to the array itself, like min, max and sum. We can use "axis" parameter to specify the direction of aggregation. If not specified. The result is for the whole array. 

In [6]:
c.sum(axis=0)  #aggregation along the columns

array([ 6,  8, 10, 12])

In [7]:
c.sum(axis=1) #aggregation along the row

array([10, 26])

In [8]:
c.sum(axis=2)  # expect error. The array does not have this dimension

ValueError: 'axis' entry is out of bounds

In [9]:
c.max(axis=0) #max along the columns

array([5, 6, 7, 8])

In [10]:
c.max()  #max of the whole array

8

## Refering to elements in an array

A 2-D matrix represented as an array can be thought of as array of arrays. Therefore, given a 2-D matrix a. We can refer to the ith row with a[i] or a[i,:]

In [11]:
c[1]  #refering to a row of a matrix

array([5, 6, 7, 8])

In [12]:
c[1,:] #equivalent to c[1]

array([5, 6, 7, 8])

In [13]:
c[1,0] #refering to individual elements of an array

5

In [14]:
c[1,0]=7 #we can assign value to individual elements of an array
c

array([[1, 2, 3, 4],
       [7, 6, 7, 8]])

In [15]:
c[1,:]=[6,6,6,6] # we can even replace the whole row by assigning an array to the corresponding index

c

array([[1, 2, 3, 4],
       [6, 6, 6, 6]])

## Sorting

the method **argsort**  returns an array of indexes of the sorted elements

In [16]:
ar=array([2,1,3,5,4])
ar.argsort() #the sorted results are not the elements of the array, but the indexes of the sorted elements

array([1, 0, 2, 4, 3])

In [17]:
argsort(ar)

array([1, 0, 2, 4, 3])

## Python list sort


## Repeat array
In numpy, we can use **tile** operation to repeat an array. **tile(array,(row,colums))** repeat array for **row** times in row, and **column** times in column.

In [18]:
ti=tile(ar,(2,1))
ti

array([[2, 1, 3, 5, 4],
       [2, 1, 3, 5, 4]])

In [19]:
it=tile(ar,(1,2))
it

array([[2, 1, 3, 5, 4, 2, 1, 3, 5, 4]])

In [20]:
tt=tile(ar,(1,2,2))
tt

array([[[2, 1, 3, 5, 4, 2, 1, 3, 5, 4],
        [2, 1, 3, 5, 4, 2, 1, 3, 5, 4]]])

## Matrix operation

In [21]:
ti

array([[2, 1, 3, 5, 4],
       [2, 1, 3, 5, 4]])

In [22]:
mat(ti)

matrix([[2, 1, 3, 5, 4],
        [2, 1, 3, 5, 4]])

In [25]:
mat(ti).transpose() * ti

matrix([[ 8,  4, 12, 20, 16],
        [ 4,  2,  6, 10,  8],
        [12,  6, 18, 30, 24],
        [20, 10, 30, 50, 40],
        [16,  8, 24, 40, 32]])